# Prometheus設定ファイル
# FX Trading System 監視設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'fx-trading-prod'
    environment: 'production'

# ルールファイルの読み込み
rule_files:
  - "alert_rules.yml"

# アラートマネージャー設定
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# スクレイプ設定
scrape_configs:
  # Prometheus自体の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter（システムメトリクス）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 5s

  # FX Trading Backend API
  - job_name: 'fx-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # FX Trading Frontend
  - job_name: 'fx-frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    params:
      target: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Nginx Reverse Proxy
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # Docker Container監視
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Celery Worker監視
  - job_name: 'celery'
    static_configs:
      - targets: ['celery-exporter:9540']
    scrape_interval: 15s

  # TimescaleDB特有メトリクス
  - job_name: 'timescale'
    static_configs:
      - targets: ['postgres:5432']
    params:
      target: ['postgres:5432']
    metrics_path: '/timescale-metrics'
    scrape_interval: 60s

  # MT5 Trading Metrics（カスタムエクスポーター）
  - job_name: 'mt5-trading'
    static_configs:
      - targets: ['backend:8001']
    metrics_path: '/trading-metrics'
    scrape_interval: 5s
    honor_labels: true

  # 機械学習モデルメトリクス
  - job_name: 'ml-model'
    static_configs:
      - targets: ['backend:8002']
    metrics_path: '/ml-metrics'
    scrape_interval: 30s

  # バックテストメトリクス
  - job_name: 'backtest'
    static_configs:
      - targets: ['backend:8003']
    metrics_path: '/backtest-metrics'
    scrape_interval: 60s

  # 外部API監視（経済指標など）
  - job_name: 'external-apis'
    static_configs:
      - targets: ['backend:8004']
    metrics_path: '/external-api-metrics'
    scrape_interval: 120s

# リモート書き込み設定（オプション：長期保存用）
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.example.com/write"
#     basic_auth:
#       username: "username"
#       password: "password"

# 保存設定
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true